import type { AnalysisResult } from "../types.js";

export class HtmlReportGenerator {
  generate(analysis: AnalysisResult): string {
    const report = analysis.report;
    const sections = [
      section("Executive summary", `<p>${escapeHtml(report.summary)}</p>`),
      section("Trust", scoreCard(report.trust.score, report.trust.level, report.trust.indicators.map((indicator) => `${indicator.weight >= 0 ? "+" : ""}${indicator.weight} ${indicator.reason}`))),
      section("Risk", scoreCard(report.risk.score, report.risk.level, report.risk.breakdown.map((item) => `${item.score >= 0 ? "+" : ""}${item.score} ${item.reason}`))),
      section("Confidence", scoreCard(report.confidence.score, "static-analysis coverage", report.confidence.explanation)),
      section("Digital signature", list([`Status: ${analysis.digitalSignature.status}`, `Publisher: ${analysis.digitalSignature.publisher ?? "Not available"}`, `Certificate issuer: ${analysis.digitalSignature.certificateIssuer ?? "Not available"}`, `Expires: ${analysis.digitalSignature.certificateExpiresAt ?? "Not available"}`, `Timestamped: ${analysis.digitalSignature.timestamped ? "Yes" : "No"}`])),
      section("Indicators", list(report.indicators)),
      section("Warnings", list(report.warnings)),
      section("Filesystem evidence", list([`Symbolic link: ${report.fileSystem.isSymbolicLink ? "Yes" : "No"}`, `Hidden by name: ${report.fileSystem.isHiddenByName ? "Yes" : "No"}`, `Zone.Identifier: ${report.fileSystem.zoneIdentifier?.zoneName ?? "Not present or unavailable"}`, ...(report.fileSystem.zoneIdentifier?.hostUrl ? [`Host URL: ${report.fileSystem.zoneIdentifier.hostUrl}`] : []), ...(report.fileSystem.zoneIdentifier?.referrerUrl ? [`Referrer URL: ${report.fileSystem.zoneIdentifier.referrerUrl}`] : [])])),
      section("Portable Executable metadata", list([`PE: ${analysis.peMetadata.isPe ? "Yes" : "No"}`, `Machine: ${analysis.peMetadata.machine ?? "Not available"}`, `Entry point: ${analysis.peMetadata.entryPointRva === undefined ? "Not available" : `0x${analysis.peMetadata.entryPointRva.toString(16)}`}`, `Image base: ${analysis.peMetadata.imageBase ?? "Not available"}`, `Subsystem: ${analysis.peMetadata.subsystem ?? "Not available"}`, `DLL characteristics: ${analysis.peMetadata.dllCharacteristics?.join(", ") || "Not available"}`, `Checksum: ${analysis.peMetadata.checksum === undefined ? "Not available" : `0x${analysis.peMetadata.checksum.toString(16)}`}`, `Image size: ${analysis.peMetadata.sizeOfImage ?? "Not available"}`, `Overlay size: ${analysis.peMetadata.overlaySize ?? "Not available"}`, `CLR metadata: ${analysis.peMetadata.clrPresent ? "Present" : "Not present"}`, `Imports: ${analysis.peMetadata.imports.length}`, `Suspicious imports: ${analysis.peMetadata.suspiciousImports.length}`, ...analysis.peMetadata.parseWarnings])),
      section("Hashes", list([`SHA-256: ${analysis.hashes.sha256}`, `SHA-1: ${analysis.hashes.sha1}`, `MD5: ${analysis.hashes.md5}`])),
    ];
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>viAI static analysis report</title><style>${styles}</style></head><body><main><header><p>viAI SECURITY</p><h1>Static analysis report</h1><span>${escapeHtml(analysis.filePath)}</span></header><section class="metrics"><div><small>Recommendation</small><strong>${escapeHtml(analysis.recommendation)}</strong></div><div><small>Risk</small><strong>${analysis.finalRiskScore}/100</strong></div><div><small>Trust</small><strong>${analysis.trustScore}/100</strong></div></section>${sections.join("")}<footer>Generated locally by viAI. This report collects static evidence and recommends next actions; it does not classify malware or determine intent.</footer></main></body></html>`;
  }
}

function section(title: string, content: string): string { return `<details open><summary>${escapeHtml(title)}</summary><div class="content">${content}</div></details>`; }
function list(values: readonly string[]): string { return values.length ? `<ul>${values.map((value) => `<li>${escapeHtml(value)}</li>`).join("")}</ul>` : "<p>No findings were recorded.</p>"; }
function scoreCard(score: number, label: string, values: readonly string[]): string { return `<p class="score"><strong>${score}/100</strong><span>${escapeHtml(label)}</span></p>${list(values)}`; }
function escapeHtml(value: string): string { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", "\"": "&quot;" })[character] ?? character); }

const styles = `:root{color-scheme:dark;font-family:Segoe UI,Arial,sans-serif}body{margin:0;background:#0c1525;color:#e8f1ff}main{max-width:920px;margin:auto;padding:42px}header{border-bottom:1px solid #29405f;padding-bottom:24px}header p{color:#6cc2df;font-weight:700;font-size:12px;letter-spacing:1.5px}h1{margin:7px 0;font-size:32px}header span,small,footer{color:#9fb2cf}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:22px 0}.metrics div,details{background:#14233a;border:1px solid #29405f;border-radius:8px}.metrics div{padding:16px}.metrics strong{display:block;margin-top:6px;font-size:20px}details{margin:12px 0}summary{cursor:pointer;padding:16px;font-weight:700}.content{padding:0 16px 16px}.score{display:flex;gap:12px;align-items:baseline}.score strong{font-size:24px;color:#75c7e6}.score span{color:#9fb2cf}li{margin:7px 0;overflow-wrap:anywhere}footer{margin-top:32px;font-size:12px;line-height:1.5}@media print{body{background:white;color:#111}main{max-width:none;padding:20px}.metrics div,details{background:white;border-color:#aaa}header span,small,footer,.score span{color:#444}.score strong{color:#14526a}details{break-inside:avoid}}`;