import { ArrowLeft, FileBadge, FolderOpen, Gauge, Hash, ShieldCheck } from "lucide-react";
import { motion } from "framer-motion";
import { useNavigate, useParams } from "react-router-dom";
import { Button, Panel, RiskBadge } from "../components/ui";
import { useSecurityStore } from "../store/securityStore";
import { pageMotion } from "../animations/motion";

export default function FileDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const item = useSecurityStore((state) => state.history.find((entry) => entry.id === id));
  if (!item) return <motion.div {...pageMotion} className="empty-report"><FileBadge size={42} /><h2>Report not found</h2><p>This local report is no longer available.</p><Button onClick={() => navigate("/history")}><ArrowLeft size={16} />Back to history</Button></motion.div>;
  const openLocation = () => void window.viai?.openPath(item.filePath);
  return <motion.div {...pageMotion} className="page-stack"><div className="page-title split-title"><div><Button onClick={() => navigate("/history")} className="secondary"><ArrowLeft size={16} />Back to history</Button><p className="eyebrow">LOCAL EVIDENCE REPORT</p><h2>{item.filePath.split(/[\\/]/).pop()}</h2><p>{item.filePath}</p></div><div className="details-actions"><Button onClick={openLocation}><FolderOpen size={16} />Open file location</Button><Button onClick={() => navigator.clipboard.writeText(JSON.stringify(item, null, 2))}>Copy report</Button></div></div><section className="report-summary"><Panel><span className="report-icon"><ShieldCheck size={25} /></span><div><span>Investigation score</span><strong>{item.finalRiskScore}<small>/100</small></strong><RiskBadge risk={item.riskLevel} /></div></Panel><Panel><Gauge size={22} /><div><span>Recommendation</span><strong className="recommendation">{item.recommendation}</strong></div></Panel></section><div className="details-grid"><DetailPanel icon={Hash} title="File and hashes" rows={[["File type", item.fileType], ["SHA-256", item.hashes.sha256], ["MD5", item.hashes.md5], ["Size", `${Math.round(item.metadata.size / 1024)} KB`]]} /><DetailPanel icon={FileBadge} title="Signature and entropy" rows={[["Signature", item.signatureStatus], ["Publisher", item.signaturePublisher ?? "Not available"], ["Entropy", item.entropy.toFixed(2)], ["Packer", item.packer.detected ? item.packer.names.join(", ") || "Possible packing" : "No indicator"]]} /><Panel className="evidence-panel"><div className="panel-heading"><div><h3>Evidence</h3><p>Signals that influenced the investigation score</p></div></div><ul>{item.evidence.map((evidence) => <li key={evidence}>{evidence}</li>)}</ul></Panel><Panel className="evidence-panel"><div className="panel-heading"><div><h3>Imported APIs</h3><p>PE metadata from the local static analyzer</p></div></div><div className="api-chips">{item.peMetadata.imports.slice(0, 16).map((api) => <code key={api}>{api}</code>)}{!item.peMetadata.imports.length && <span>No PE imports available.</span>}</div></Panel></div></motion.div>;
}

function DetailPanel({ icon: Icon, title, rows }: { icon: typeof Hash; title: string; rows: string[][] }) { return <Panel className="detail-panel"><div className="panel-heading"><Icon size={18} /><h3>{title}</h3></div>{rows.map(([label, value]) => <div className="detail-row" key={label}><span>{label}</span><code>{value}</code></div>)}</Panel>; }