import { useDeferredValue, useEffect, useState } from "react";
import { Download, FileJson, Search, SlidersHorizontal, Trash2 } from "lucide-react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import { Button, ConfirmDialog, DropdownMenu, Panel, Skeleton } from "../components/ui";
import { presentAssessment } from "../assessmentPresentation";
import { pageMotion } from "../animations/motion";

interface PersistedRecord { id: string; kind: string; occurredAt: string; detail: string; fileHash?: string; filePath?: string; recommendation?: string; matchedRules?: string[]; engineVersion: string; assessment?: unknown; baselineState?: string; }
interface BackgroundSnapshot { history: PersistedRecord[]; }
type AssessmentFilter = "all" | "needs-investigation" | "no-follow-up" | "legacy";
const filters = [{ value: "all", label: "All assessments" }, { value: "needs-investigation", label: "Needs investigation" }, { value: "no-follow-up", label: "No follow-up" }, { value: "legacy", label: "Legacy reports" }] as const;
const rowHeight = 84;

export default function History() {
  const [persisted, setPersisted] = useState<PersistedRecord[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<AssessmentFilter>("all");
  const [scrollTop, setScrollTop] = useState(0);
  const deferredQuery = useDeferredValue(query);
  useEffect(() => { let mounted = true; void (async () => { try { const value = await window.viai?.background.snapshot(); if (mounted && value) setPersisted((value as BackgroundSnapshot).history ?? []); } finally { if (mounted) setLoaded(true); } })(); return window.viai?.background.onChanged((value) => { if (mounted && value) { setPersisted((value as BackgroundSnapshot).history ?? []); setLoaded(true); } }); }, []);
  if (!loaded) return <motion.div {...pageMotion} className="page-stack history-loading-skeleton" aria-busy="true"><div><Skeleton className="history-skeleton-title" /><Skeleton className="history-skeleton-copy" /></div><Panel className="history-skeleton-panel"><div className="history-skeleton-toolbar"><Skeleton /><Skeleton /></div>{Array.from({ length: 6 }, (_, index) => <div className="history-skeleton-row" key={index}><Skeleton /><div><Skeleton /><Skeleton /></div><Skeleton /></div>)}</Panel></motion.div>;
  const records = persisted.map((record) => ({ ...record, presentation: presentAssessment(record, record.engineVersion), rules: record.matchedRules ?? [] })).sort((left, right) => right.occurredAt.localeCompare(left.occurredAt));
  const results = records.filter((item) => `${item.filePath ?? ""} ${item.detail} ${item.presentation.verdict} ${item.presentation.recommendation}`.toLowerCase().includes(deferredQuery.toLowerCase()) && matchesFilter(item.presentation, filter));
  const first = Math.max(0, Math.floor(scrollTop / rowHeight) - 4);
  const visible = results.slice(first, Math.min(results.length, first + 18));
  const selectedLabel = filters.find((option) => option.value === filter)?.label ?? "All assessments";
  const exportJson = () => download(JSON.stringify(results, null, 2), "viai-analysis-history.json", "application/json");
  return <motion.div {...pageMotion} className="page-stack"><div className="page-title split-title"><div><p className="eyebrow">LOCAL RECORDS</p><h2>Analysis history</h2><p>Canonical assessments, supporting evidence, and legacy reports remain available for local review.</p></div><div className="history-actions"><ClearDataControl /><HistoryClearControl /><Button onClick={exportJson} disabled={!results.length}><Download size={16} />Export JSON</Button></div></div><Panel className="history-panel"><div className="toolbar"><div className="history-filters"><label className="search-box"><Search size={17} /><span className="sr-only">Search analysis history</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search files and assessments" /></label><DropdownMenu ariaLabel="Filter by assessment" label={selectedLabel} value={filter} options={filters} onChange={(value) => setFilter(value as AssessmentFilter)} icon={SlidersHorizontal} /></div><span>{results.length} record{results.length === 1 ? "" : "s"}</span></div>{results.length ? <div className="history-viewport" onScroll={(event) => setScrollTop(event.currentTarget.scrollTop)}><div className="history-virtual-list" style={{ height: results.length * rowHeight }}>{visible.map((item, offset) => <div className="history-row" key={item.id} style={{ transform: `translateY(${(first + offset) * rowHeight}px)` }}><FileJson size={18} className="file-icon" /><div className="file-cell"><strong title={item.filePath}>{item.filePath?.split(/[\\/]/).pop() ?? item.detail}</strong><span>{new Date(item.occurredAt).toLocaleString()} - {item.presentation.recommendation} - {item.presentation.modelLabel}</span><span>{item.rules.length ? `Rules: ${item.rules.join(", ")}` : item.presentation.baselineState}</span></div><strong className="recommendation">{item.presentation.verdict}</strong><strong className="score-cell">{item.presentation.priority}</strong><Link className="text-link" to={`/details/${item.id}`}>View details</Link></div>)}</div></div> : <div className="empty-state"><FileJson size={30} /><div><strong>No matching local records</strong><p>Completed analyses and local events will appear here.</p></div></div>}</Panel></motion.div>;
}

function matchesFilter(presentation: ReturnType<typeof presentAssessment>, filter: AssessmentFilter): boolean { if (filter === "all") return true; if (filter === "legacy") return presentation.model === "legacy"; const investigate = ["MEDIUM", "HIGH", "URGENT"].includes(presentation.priority) || ["REVIEW", "DYNAMIC_ANALYSIS"].includes(presentation.recommendation); return filter === "needs-investigation" ? presentation.model === "v0.3" && investigate : presentation.model === "v0.3" && !investigate; }
function HistoryClearControl() { const [open, setOpen] = useState(false); const [clearing, setClearing] = useState(false); const confirm = async () => { setClearing(true); try { await window.viai?.background.clearHistory("all"); setOpen(false); toast.success("Local history cleared."); } catch { toast.error("Could not clear local history."); } finally { setClearing(false); } }; return <><Button className="danger" onClick={() => setOpen(true)}><Trash2 size={16} />Clear history</Button><ConfirmDialog open={open} title="Clear local history" detail="This removes all local analysis records. This cannot be undone." confirmLabel={clearing ? "Clearing..." : "Clear history"} onCancel={() => setOpen(false)} onConfirm={() => void confirm()} /></>; }
function ClearDataControl() { const [open, setOpen] = useState(false); const [clearing, setClearing] = useState(false); const confirm = async () => { setClearing(true); try { await window.viai?.application.clearLocalData(); setOpen(false); toast.success("Local scan data cleared."); } catch { toast.error("Could not clear local data."); } finally { setClearing(false); } }; return <><Button className="danger" onClick={() => setOpen(true)}><Trash2 size={16} />Clear data</Button><ConfirmDialog open={open} title="Clear local data?" detail="This removes local scan history, active scan state, device records, trust decisions, settings, and cached hash reputation. It does not remove files from your computer." confirmLabel={clearing ? "Clearing..." : "Clear local data"} onCancel={() => setOpen(false)} onConfirm={() => void confirm()} /></>; }
function download(content: BlobPart, filename: string, type: string): void { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }