import { useDeferredValue, useEffect, useState } from "react";
import { Download, FileJson, Search, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { Button, Panel, RiskBadge } from "../components/ui";
import { useSecurityStore } from "../store/securityStore";
import { pageMotion } from "../animations/motion";

interface PersistedRecord { id: string; kind: string; occurredAt: string; detail: string; fileHash?: string; filePath?: string; riskScore?: number; trustScore?: number; recommendation?: string; matchedRules?: string[]; engineVersion: string; }
interface BackgroundSnapshot { history: PersistedRecord[]; }

export default function History() {
  const session = useSecurityStore((state) => state.history);
  const [persisted, setPersisted] = useState<PersistedRecord[]>([]);
  const [query, setQuery] = useState("");
  const [riskFilter, setRiskFilter] = useState<"all" | "low" | "medium" | "high">("all");
  const deferredQuery = useDeferredValue(query);
  useEffect(() => { let mounted = true; void window.viai?.background.snapshot().then((value) => { if (mounted && value) setPersisted((value as BackgroundSnapshot).history ?? []); }); return window.viai?.background.onChanged((value) => { if (mounted && value) setPersisted((value as BackgroundSnapshot).history ?? []); }); }, []);
  const records = [...persisted.map((record) => ({ id: record.id, filePath: record.filePath, occurredAt: record.occurredAt, risk: risk(record.riskScore), score: record.riskScore ?? 0, detail: record.detail, trust: record.trustScore, recommendation: record.recommendation, rules: record.matchedRules ?? [], sessionId: undefined as string | undefined })), ...session.map((item) => ({ id: `session-${item.id}`, filePath: item.filePath, occurredAt: item.analyzedAt, risk: item.riskLevel, score: item.finalRiskScore, detail: "Detailed report available for this session.", trust: item.trustScore, recommendation: item.recommendation, rules: [], sessionId: item.id }))].sort((left, right) => right.occurredAt.localeCompare(left.occurredAt));
  const results = records.filter((item) => `${item.filePath ?? ""} ${item.detail}`.toLowerCase().includes(deferredQuery.toLowerCase()) && (riskFilter === "all" || item.risk === riskFilter));
  const exportJson = () => { const blob = new Blob([JSON.stringify(results, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "viai-analysis-history.json"; anchor.click(); URL.revokeObjectURL(url); };
  return <motion.div {...pageMotion} className="page-stack"><div className="page-title split-title"><div><p className="eyebrow">LOCAL RECORDS</p><h2>Analysis history</h2><p>Lightweight report metadata, recommendations, trust evidence, and rule matches stay on this device until cleared.</p></div><Button onClick={exportJson} disabled={!results.length}><Download size={16} />Export JSON</Button></div><Panel className="history-panel"><div className="toolbar"><div className="history-filters"><label className="search-box"><Search size={17} /><span className="sr-only">Search analysis history</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search files and local events" /></label><label className="history-filter"><SlidersHorizontal size={16} /><span className="sr-only">Filter by risk level</span><select value={riskFilter} onChange={(event) => setRiskFilter(event.target.value as typeof riskFilter)} aria-label="Filter by risk level"><option value="all">All risk levels</option><option value="low">Low risk</option><option value="medium">Medium risk</option><option value="high">High risk</option></select></label></div><span>{results.length} record{results.length === 1 ? "" : "s"}</span></div>{results.length ? <div className="history-table">{results.map((item) => <div className="history-row" key={item.id}><FileJson size={18} className="file-icon" /><div className="file-cell"><strong>{item.filePath?.split(/[\\/]/).pop() ?? item.detail}</strong><span>{new Date(item.occurredAt).toLocaleString()} - {item.recommendation ?? "Local event"} - trust {item.trust ?? 0}</span><span>{item.rules.length ? `Rules: ${item.rules.join(", ")}` : item.detail}</span></div><RiskBadge risk={item.risk} /><strong className="score-cell">{item.score}</strong>{item.sessionId ? <Link className="text-link" to={`/details/${item.sessionId}`}>View details</Link> : <span className="text-link history-persistent"><ShieldCheck size={15} />Stored locally</span>}</div>)}</div> : <div className="empty-state"><FileJson size={30} /><div><strong>No matching local records</strong><p>Completed analyses and realtime events will appear here.</p></div></div>}</Panel></motion.div>;
}

function risk(score: number | undefined): "low" | "medium" | "high" { return (score ?? 0) <= 25 ? "low" : (score ?? 0) <= 60 ? "medium" : "high"; }