import { useDeferredValue, useEffect, useRef, useState } from "react";
import type { ChangeEvent } from "react";
import { Bell, Cpu, Download, FolderCog, HardDrive, History, Power, RotateCcw, Search, Settings2, ShieldCheck, SlidersHorizontal, Upload } from "lucide-react";
import { motion } from "framer-motion";
import toast from "react-hot-toast";
import { Button, Panel, Toggle } from "../components/ui";
import { pageMotion } from "../animations/motion";

type Settings = Record<string, boolean | string | number | string[]>;
interface Snapshot { settings: Settings; history: unknown[]; activeMonitors: string[]; }
const empty: Snapshot = { settings: {}, history: [], activeMonitors: [] };

const groups: Array<{ title: string; icon: typeof Power; advanced?: boolean; options: Array<[string, string, string]> }> = [
  { title: "General", icon: Power, options: [["backgroundProtection", "Enable Background Protection", "Runs enabled local monitors even when the desktop window is hidden."], ["runAfterWindowCloses", "Run after window closes", "Closing the desktop window hides it and leaves background protection running."], ["launchOnStartup", "Launch viAI on Windows startup", "Uses Windows login-item registration for this local desktop application."], ["startMinimized", "Start minimized", "Minimizes the window when viAI is launched at sign-in."], ["startSilently", "Start silently in background", "At Windows startup, starts without opening a visible window."], ["openDashboardAfterStartup", "Open dashboard after startup", "Shows the dashboard when viAI starts normally."], ["minimizeToTray", "Minimize to tray", "Hides the window when minimized; use the tray icon to restore it."], ["windowsNotifications", "Enable Windows notifications", "Shows native Windows notifications only for selected local events."], ["soundNotifications", "Enable sound notifications", "Allows Windows to play notification sounds."]] },
  { title: "File Monitoring", icon: FolderCog, options: [["monitorFileCreation", "Monitor file creation", "Observes eligible candidate files newly created in enabled locations."], ["monitorFileModification", "Monitor file modification", "Observes eligible candidate files when modified."], ["monitorFileRename", "Monitor file rename", "Uses filesystem rename events to detect candidate file arrivals."], ["monitorFileDeletion", "Monitor file deletion", "Reserved for future file lifecycle telemetry."], ["monitorDownloads", "Monitor Downloads folder", "Enables the existing local download candidate monitor."], ["monitorDesktop", "Monitor Desktop", "Enables local candidate observation on the Desktop."], ["monitorDocuments", "Monitor Documents", "Enables local candidate observation in Documents."], ["monitorUsbStorage", "Monitor USB storage", "Delegates removable media observation to Device Security."], ["monitorNetworkShares", "Monitor network shares", "Enterprise placeholder; network share monitoring is not implemented yet."]] },
  { title: "Scan Types", icon: ShieldCheck, options: [["scanExecutables", "Scan executables", "Include executable candidates in local static analysis."], ["scanDlls", "Scan DLLs", "Include dynamic-link libraries in candidate discovery."], ["scanScripts", "Scan scripts", "Include supported script files in candidate discovery."], ["scanOfficeDocuments", "Scan Office documents", "Enable Office document candidate handling for future macro-focused analysis."], ["scanArchives", "Scan archives", "Enable archive candidates without extracting or executing content."], ["scanPdfs", "Scan PDFs", "Enable PDF candidate handling for future static inspection."], ["scanInstallers", "Scan installers", "Include common installer files in local static analysis."], ["scanShortcuts", "Scan shortcuts (.lnk)", "Enable shortcut candidate handling for future target resolution."], ["scanBatchFiles", "Scan batch files", "Include CMD and batch files in candidate discovery."], ["scanPowerShellScripts", "Scan PowerShell scripts", "Include PowerShell scripts in candidate discovery."], ["scanJavaScriptFiles", "Scan JavaScript files", "Include JavaScript and Windows Script Host candidates."], ["scanPythonScripts", "Scan Python scripts", "Enable Python script candidate handling."], ["scanUnknownFileTypes", "Scan unknown file types", "Reserved for an explicit future unknown-type policy."]] },
  { title: "Download Protection", icon: Download, options: [["automaticDownloadScan", "Automatically scan downloaded files", "Submits eligible downloaded files to the existing local analysis pipeline."], ["scanBrowserDownloads", "Scan browser downloads", "Applies download monitoring to browser-managed Downloads paths."], ["scanTorrentDownloads", "Scan torrent downloads", "Placeholder for future download-source attribution."], ["scanCompressedDownloads", "Scan compressed downloads", "Enables archive candidates without extracting contents."], ["delayExecutionUntilScanCompletes", "Delay execution until scan completes", "Future policy placeholder; viAI does not block execution."]] },
  { title: "USB Monitoring", icon: HardDrive, options: [["monitorUsbInsertion", "Monitor USB insertion", "Records Windows Plug and Play arrival events."], ["automaticallyScanUsb", "Automatically scan USB storage", "Submits eligible files on removable storage through the existing local engine."], ["monitorExternalSsd", "Monitor external SSD", "Classifies and displays external SSDs when Windows reports them."], ["monitorExternalHdd", "Monitor external HDD", "Classifies and displays external HDDs when Windows reports them."], ["monitorSdCards", "Monitor SD cards", "Classifies and displays removable SD storage when Windows reports it."], ["monitorSmartphones", "Monitor smartphones", "Tracks MTP/PTP device arrival only; no phone content is scanned."], ["monitorUnknownUsbDevices", "Monitor unknown USB devices", "Records unknown USB hardware for local review."]] },
  { title: "Process Monitoring", icon: Cpu, advanced: true, options: [["monitorNewProcesses", "Monitor newly launched processes", "Observes new Windows processes and submits their executable path to local static analysis."], ["monitorChildProcesses", "Monitor child processes", "Includes newly observed child-process activity in local process observation."], ["monitorSuspiciousCommandLines", "Monitor suspicious command line arguments", "Selects new processes with high-signal command patterns for local executable analysis; command lines are not retained."], ["monitorPowerShell", "Monitor PowerShell", "Observes new PowerShell hosts and analyzes their executable path locally."], ["monitorCmd", "Monitor CMD", "Observes new CMD hosts and analyzes their executable path locally."], ["monitorWScript", "Monitor WScript", "Observes new Windows Script Host processes and analyzes their executable path locally."], ["monitorMshta", "Monitor MSHTA", "Observes new MSHTA processes and analyzes their executable path locally."]] },
  { title: "Windows Monitoring", icon: Settings2, advanced: true, options: [["monitorStartupFolder", "Monitor Startup Folder", "Watches candidate files in the current user's Windows Startup folder."], ["monitorScheduledTasks", "Monitor Scheduled Tasks", "Read-only observation records scheduled-task additions or changes locally."], ["monitorRegistryRunKeys", "Monitor Registry Run Keys", "Read-only observation records Windows Run-key additions or changes locally."], ["monitorServices", "Monitor Services", "Read-only observation records service additions or changes locally."], ["monitorDrivers", "Monitor Drivers", "Read-only observation records driver additions or changes locally."]] },
  { title: "Notifications", icon: Bell, options: [["notifySafeScan", "Safe Scan", "Notify when a completed scan has low-risk evidence."], ["notifyMediumRisk", "Medium Risk", "Notify when a completed scan needs investigation."], ["notifyHighRisk", "High Risk", "Notify when evidence requires urgent investigation."], ["notifyUsbConnected", "USB Connected", "Notify when Device Security records a USB arrival."], ["notifyUsbRemoved", "USB Removed", "Notify when Device Security records a USB removal."], ["notifyBackgroundStarted", "Background Started", "Notify when background protection starts."], ["notifyBackgroundStopped", "Background Stopped", "Reserved for an explicit background stop event."], ["notifyEngineUpdates", "Engine Updates", "Reserved for future signed local engine updates."], ["notifyScanCompleted", "Scan Completed", "Notify when a local scan reaches completion."]] },
];

export default function Realtime() {
  const [snapshot, setSnapshot] = useState<Snapshot>(empty);
  const [query, setQuery] = useState("");
  const [advanced, setAdvanced] = useState(false);
  const importRef = useRef<HTMLInputElement>(null);
  const deferredQuery = useDeferredValue(query.trim().toLowerCase());
  useEffect(() => { let mounted = true; void window.viai?.background.snapshot().then((value) => { if (mounted && value) setSnapshot(value as Snapshot); }); return window.viai?.background.onChanged((value) => { if (mounted && value) setSnapshot(value as Snapshot); }); }, []);
  const update = async (changes: Record<string, unknown>) => { try { const next = await window.viai?.background.update(changes); if (next) setSnapshot(next as Snapshot); } catch { toast.error("Could not save realtime protection settings."); } };
  const toggle = (key: string) => void update({ [key]: snapshot.settings[key] !== true });
  const choosePath = async (key: "customFolders" | "excludedFolders" | "excludedFiles") => { const path = key === "excludedFiles" ? await window.viai?.chooseFile() : await window.viai?.chooseFolder(); if (!path) return; const values = list(snapshot.settings[key]); if (!values.includes(path)) await update({ [key]: [...values, path] }); };
  const removePath = (key: "customFolders" | "excludedFolders" | "excludedFiles", path: string) => void update({ [key]: list(snapshot.settings[key]).filter((entry) => entry !== path) });
  const restore = async (kind: "recommended" | "factory") => { const next = kind === "recommended" ? await window.viai?.background.restoreRecommended() : await window.viai?.background.restoreFactory(); if (next) { setSnapshot(next as Snapshot); toast.success(kind === "recommended" ? "Recommended settings restored." : "Factory defaults restored."); } };
  const exportSettings = async () => { const serialized = await window.viai?.background.exportSettings(); if (!serialized) return; const blob = new Blob([serialized], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "viai-realtime-settings.json"; link.click(); URL.revokeObjectURL(url); };
  const importSettings = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { const next = await window.viai?.background.importSettings(await file.text()); if (next) { setSnapshot(next as Snapshot); toast.success("Settings imported locally."); } } catch { toast.error("That settings file is invalid."); } finally { event.target.value = ""; } };
  const visible = groups.filter((group) => (!group.advanced || advanced) && (!deferredQuery || group.title.toLowerCase().includes(deferredQuery) || group.options.some(([, label, detail]) => `${label} ${detail}`.toLowerCase().includes(deferredQuery))));
  return <motion.div {...pageMotion} className="page-stack realtime-page"><div className="page-title split-title"><div><p className="eyebrow">BACKGROUND MONITORING</p><h2>Realtime Protection</h2><p>Every setting stays on this device. viAI collects evidence and recommends next steps; it never deletes or quarantines files.</p></div><div className="realtime-state"><span className={snapshot.settings.backgroundProtection === true ? "status-dot ready" : "status-dot"} />{snapshot.settings.backgroundProtection === true ? "Protection active" : "Protection paused"}</div></div><Panel className="recommended-panel"><div><span className="recommendation-mark"><ShieldCheck size={20} /></span><div><h3>Recommended by viAI: Balanced Protection</h3><p>Downloads, executable candidates, scripts, USB monitoring, notifications, and Windows startup are enabled. Registry, driver, and network monitoring remain off until their evidence collectors exist.</p></div></div><Button onClick={() => void restore("recommended")}>Restore recommended</Button></Panel><div className="realtime-toolbar"><label className="search-box"><Search size={17} /><span className="sr-only">Search realtime settings</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search protection settings" /></label><Button onClick={() => setAdvanced((value) => !value)}><SlidersHorizontal size={15} />{advanced ? "Hide advanced" : "Show advanced"}</Button><span>{snapshot.activeMonitors.length} active monitor{snapshot.activeMonitors.length === 1 ? "" : "s"}</span></div>{visible.map((group) => <SettingsGroup key={group.title} {...group} settings={snapshot.settings} toggle={toggle} query={deferredQuery} />)}<AutomaticActions settings={snapshot.settings} update={update} /><Performance settings={snapshot.settings} update={update} /><Exclusions settings={snapshot.settings} choosePath={choosePath} removePath={removePath} update={update} /><Panel className="realtime-reset"><div><h3>Local settings and history</h3><p>Export and import settings locally, clear lightweight report metadata, or return to factory defaults.</p></div><div><Button onClick={exportSettings}><Upload size={15} />Export</Button><Button onClick={() => importRef.current?.click()}><Download size={15} />Import</Button><Button className="danger" onClick={() => void window.viai?.background.clearHistory().then(() => toast.success("Background history cleared."))}><History size={15} />Clear history</Button><Button className="danger" onClick={() => void restore("factory")}><RotateCcw size={15} />Factory defaults</Button><input ref={importRef} type="file" accept="application/json" className="sr-only" onChange={importSettings} /></div></Panel></motion.div>;
}

function SettingsGroup({ title, icon: Icon, options, settings, toggle, query }: { title: string; icon: typeof Power; options: Array<[string, string, string]>; settings: Settings; toggle: (key: string) => void; query: string }) { const visible = options.filter(([, label, detail]) => !query || `${label} ${detail}`.toLowerCase().includes(query)); if (!visible.length) return null; return <Panel className="realtime-section"><div className="setting-heading"><Icon size={18} /><h3>{title}</h3></div>{visible.map(([key, label, detail]) => <div className="setting-row" key={key}><div><strong>{label}</strong><p title={detail}>{detail}</p></div><Toggle checked={settings[key] === true} label={label} onChange={() => toggle(key)} /></div>)}</Panel>; }
function AutomaticActions({ settings, update }: { settings: Settings; update: (changes: Record<string, unknown>) => Promise<void> }) { return <Panel className="realtime-section"><div className="setting-heading"><ShieldCheck size={18} /><h3>Automatic Actions</h3></div><p className="section-note">Actions are recommendations only. viAI never quarantines or deletes files.</p><Choice label="Medium risk" value={String(settings.mediumRiskAction ?? "sandbox")} options={[["ignore", "Ignore"], ["notify", "Notify"], ["sandbox", "Recommend Sandbox"], ["ai", "Recommend AI"]]} onChange={(value) => void update({ mediumRiskAction: value })} /><Choice label="High risk" value={String(settings.highRiskAction ?? "ai")} options={[["notify", "Notify"], ["sandbox", "Recommend Sandbox"], ["ai", "Recommend AI"]]} onChange={(value) => void update({ highRiskAction: value })} /></Panel>; }
function Performance({ settings, update }: { settings: Settings; update: (changes: Record<string, unknown>) => Promise<void> }) { return <Panel className="realtime-section"><div className="setting-heading"><Cpu size={18} /><h3>Performance</h3></div><Choice label="Scan mode" value={String(settings.performanceMode ?? "balanced")} options={[["light", "Light"], ["balanced", "Balanced"], ["deep", "Deep"]]} onChange={(value) => void update({ performanceMode: value })} /><Choice label="Scan priority" value={String(settings.scanPriority ?? "normal")} options={[["low", "Low"], ["normal", "Normal"], ["high", "High"]]} onChange={(value) => void update({ scanPriority: value })} /><Choice label="Maximum parallel scans" value={String(settings.maximumParallelScans ?? 0)} options={[["0", "Automatic"], ["1", "1"], ["2", "2"], ["4", "4"], ["8", "8"]]} onChange={(value) => void update({ maximumParallelScans: Number(value) })} /></Panel>; }
function Choice({ label, value, options, onChange }: { label: string; value: string; options: Array<[string, string]>; onChange: (value: string) => void }) { return <fieldset className="choice-row"><legend>{label}</legend><div>{options.map(([id, text]) => <label key={id}><input type="radio" name={label} checked={value === id} onChange={() => onChange(id)} />{text}</label>)}</div></fieldset>; }
function Exclusions({ settings, choosePath, removePath, update }: { settings: Settings; choosePath: (key: "customFolders" | "excludedFolders" | "excludedFiles") => Promise<void>; removePath: (key: "customFolders" | "excludedFolders" | "excludedFiles", path: string) => void; update: (changes: Record<string, unknown>) => Promise<void> }) { return <Panel className="realtime-section"><div className="setting-heading"><FolderCog size={18} /><h3>Exclusions</h3></div><p className="section-note">Exclusions are local configuration only. Trusted publisher exclusions remain a future policy provider.</p><PathList title="Custom folders" values={list(settings.customFolders)} onAdd={() => void choosePath("customFolders")} onRemove={(value) => removePath("customFolders", value)} /><PathList title="Excluded folders" values={list(settings.excludedFolders)} onAdd={() => void choosePath("excludedFolders")} onRemove={(value) => removePath("excludedFolders", value)} /><PathList title="Excluded files" values={list(settings.excludedFiles)} onAdd={() => void choosePath("excludedFiles")} onRemove={(value) => removePath("excludedFiles", value)} /><TextList title="Excluded extensions" values={list(settings.excludedExtensions)} onChange={(values) => void update({ excludedExtensions: values })} /><TextList title="Excluded processes" values={list(settings.excludedProcesses)} onChange={(values) => void update({ excludedProcesses: values })} /></Panel>; }
function PathList({ title, values, onAdd, onRemove }: { title: string; values: string[]; onAdd: () => void; onRemove: (value: string) => void }) { return <div className="path-list"><div><strong>{title}</strong><Button onClick={onAdd}>Add</Button></div>{values.map((value) => <span key={value}><code>{value}</code><button type="button" onClick={() => onRemove(value)} aria-label={`Remove ${value}`}>x</button></span>)}</div>; }
function TextList({ title, values, onChange }: { title: string; values: string[]; onChange: (values: string[]) => void }) { return <label className="text-list"><strong>{title}</strong><input value={values.join(", ")} placeholder="Comma-separated values" onChange={(event) => onChange(event.target.value.split(",").map((value) => value.trim()).filter(Boolean))} /></label>; }
function list(value: Settings[string] | undefined): string[] { return Array.isArray(value) ? value.filter((entry): entry is string => typeof entry === "string") : []; }