import { Bot, Cloud, Cpu, Languages, Moon, Network, ShieldAlert, SlidersHorizontal } from "lucide-react";
import { motion } from "framer-motion";
import { Panel, Toggle } from "../components/ui";
import { useSecurityStore } from "../store/securityStore";
import { pageMotion } from "../animations/motion";

export default function Settings() {
  const state = useSecurityStore();
  return <motion.div {...pageMotion} className="page-stack"><div className="page-title"><p className="eyebrow">APPLICATION PREFERENCES</p><h2>Settings</h2><p>Control how the desktop app presents and schedules local analysis.</p></div><section className="settings-grid"><Panel><div className="setting-heading"><Moon size={18} /><h3>Appearance</h3></div><div className="setting-row"><div><strong>Dark mode</strong><p>Use the reduced-glare desktop theme.</p></div><Toggle checked={state.darkMode} label="Toggle dark mode" onChange={() => state.setDarkMode(!state.darkMode)} /></div><div className="setting-row"><div><strong>Language</strong><p>English (United States)</p></div><Languages size={18} /></div></Panel><Panel><div className="setting-heading"><Cpu size={18} /><h3>Performance</h3></div><label className="select-setting"><span>Scan mode</span><select value={state.performanceMode} onChange={(event) => state.setPerformanceMode(event.target.value as typeof state.performanceMode)}><option value="quiet">Quiet</option><option value="balanced">Balanced</option><option value="performance">Performance</option></select></label><label className="range-setting"><span>Analysis concurrency <strong>{state.threadCount}</strong></span><input type="range" min="1" max="8" value={state.threadCount} onChange={(event) => state.setThreadCount(Number(event.target.value))} /></label></Panel><Panel className="coming-soon"><div className="setting-heading"><SlidersHorizontal size={18} /><h3>Future modules</h3></div><div className="future-grid"><Future icon={Bot} name="AI Investigation" /><Future icon={Cloud} name="Cloud Reputation" /><Future icon={ShieldAlert} name="Zero-Day Detection" /><Future icon={Network} name="Network Monitor" /></div></Panel></section></motion.div>;
}

function Future({ icon: Icon, name }: { icon: typeof Bot; name: string }) { return <div><Icon size={17} /><span>{name}</span><small>Coming soon</small></div>; }