import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { Activity, Archive, Cpu, FileArchive, FileCode2, FileSearch, FolderSearch, HardDrive, Play, RefreshCw, ScanSearch, ShieldCheck, TriangleAlert, Upload, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";
import { Panel, RiskBadge } from "../ui";

export interface SystemOverview { device: { id: string; computerName: string; currentUser: string; architecture: string; uptimeSeconds: number }; operatingSystem: { edition: string; version: string; build: string; kernel: string }; hardware: { bios: string; motherboard: string; cpu: string; cores: number; threads: number; totalMemory: number; availableMemory: number; memoryUsagePercent: number; gpu: string }; network: { ipAddress: string; macAddress: string }; storage: Array<{ drive: string; capacity: number; free: number; filesystem: string }>; health: { cpuUsagePercent: number; memoryUsagePercent: number; diskUsagePercent?: number }; }
export interface AnalysisItem { id: string; filePath: string; analyzedAt: string; finalRiskScore: number; riskLevel: "low" | "medium" | "high"; recommendation: string; metadata: { extension?: string }; }
export interface ScanOverview { active: boolean; completed: number; total: number; cacheHits?: number; cacheSkipped?: number; workersActive?: number; workersTotal?: number; throughputPerSecond?: number; estimatedRemainingMs?: number; currentPath: string; }
export interface ScanStats { total: number; executables: number; dlls: number; drivers: number; scripts: number; documents: number; archives: number; media: number; suspicious: number; investigated: number; skipped?: number; cached: number; }

export function DeviceInformationCard({ system }: { system?: SystemOverview }) { const values = system ? [["Computer name", system.device.computerName], ["Current user", system.device.currentUser], ["Windows edition", system.operatingSystem.edition], ["Version / build", `${system.operatingSystem.version} (${system.operatingSystem.build})`], ["Architecture", system.device.architecture], ["Kernel", system.operatingSystem.kernel], ["System uptime", duration(system.device.uptimeSeconds)], ["BIOS", system.hardware.bios], ["Motherboard", system.hardware.motherboard], ["CPU", system.hardware.cpu], ["CPU cores / threads", `${system.hardware.cores} / ${system.hardware.threads}`], ["Installed RAM", bytes(system.hardware.totalMemory)], ["Available RAM", bytes(system.hardware.availableMemory)], ["RAM usage", `${system.hardware.memoryUsagePercent}%`], ["GPU", system.hardware.gpu], ["IP address", system.network.ipAddress], ["MAC address", system.network.macAddress], ["Device ID", system.device.id]] : [];
  return <Panel className="overview-device-card"><div className="panel-heading"><div><p className="eyebrow">DEVICE INFORMATION</p><h3>{system?.device.computerName ?? "Loading local device details"}</h3><p>Local identity, operating system, and hardware inventory.</p></div><span className="overview-card-icon"><Cpu size={20} /></span></div><div className="overview-device-grid">{values.length ? values.map(([label, value]) => <Info key={label} label={label} value={value} />) : <Unavailable />}</div><div className="future-controls" aria-label="Reserved future device controls"><span>Device controls</span><button type="button" disabled>Rename</button><button type="button" disabled>Restart</button><button type="button" disabled>Shutdown</button><button type="button" disabled>Policies</button></div></Panel>; }

export function ProtectionCard({ engineOnline, protectionEnabled, version, lastScan }: { engineOnline: boolean; protectionEnabled: boolean; version: string; lastScan?: string }) { const active = engineOnline && protectionEnabled; return <Panel className="overview-protection-card"><div className="panel-heading"><div><p className="eyebrow">PROTECTION STATUS</p><h3>{active ? "Protection active" : "Protection needs attention"}</h3></div><span className={`overview-status ${active ? "healthy" : "warning"}`}><ShieldCheck size={17} />{active ? "Healthy" : "Review"}</span></div><div className="overview-list"><Info label="Realtime protection" value={protectionEnabled ? "Enabled" : "Disabled"} /><Info label="Engine status" value={engineOnline ? "Connected" : "Offline"} /><Info label="Definitions version" value="Not Available" /><Info label="Engine version" value={version} /><Info label="Last scan" value={lastScan ? dateTime(lastScan) : "Not Available"} /><Info label="Last update" value="Not Available" /><Info label="Security health" value={active ? "Healthy" : "Needs attention"} /></div></Panel>; }

export function StatisticsCard({ stats }: { stats: ScanStats }) { const cards: Array<[string, number | string, typeof FileSearch]> = [["Files ever scanned", stats.total, FileSearch], ["Executables", stats.executables, FileCode2], ["DLLs", stats.dlls, FileCode2], ["Drivers", stats.drivers, Cpu], ["Scripts", stats.scripts, FileCode2], ["Documents", stats.documents, FileSearch], ["Archives", stats.archives, FileArchive], ["Media", stats.media, Archive], ["Skipped files", stats.skipped === undefined ? "Not Available" : stats.skipped, TriangleAlert], ["Cached results", stats.cached, RefreshCw], ["Suspicious files", stats.suspicious, TriangleAlert], ["Investigated files", stats.investigated, UsersRound], ["Quarantined files", "Not Available", ShieldCheck]]; return <Panel className="overview-statistics"><div className="panel-heading"><div><p className="eyebrow">SCAN STATISTICS</p><h3>Local analysis inventory</h3><p>Counts are calculated from the local viAI database.</p></div></div><div className="overview-stat-grid">{cards.map(([label, value, Icon]) => <div key={label}><Icon size={15} /><span>{label}</span><strong>{typeof value === "number" ? formatCount(value) : value}</strong></div>)}</div></Panel>; }

export function ActivityCard({ activity }: { activity: Array<{ day: string; value: number }> }) { const total = activity.reduce((sum, point) => sum + point.value, 0); return <Panel className="overview-chart"><div className="panel-heading"><div><p className="eyebrow">ANALYSIS ACTIVITY</p><h3>Daily files scanned</h3><p>Last 30 days, based on local analysis records.</p></div><strong className="overview-total">{formatCount(total)}</strong></div><div className="overview-chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activity}><defs><linearGradient id="overviewActivity" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#397ec1" stopOpacity={0.35} /><stop offset="100%" stopColor="#397ec1" stopOpacity={0} /></linearGradient></defs><Tooltip formatter={(value) => [formatCount(Number(value)), "Files scanned"]} /><Area type="monotone" dataKey="value" stroke="#2f80b8" strokeWidth={2.5} fill="url(#overviewActivity)" isAnimationActive={false} /></AreaChart></ResponsiveContainer></div></Panel>; }

export function RiskDistributionCard({ values }: { values: Array<{ name: string; value: number; color: string }> }) { const total = values.reduce((sum, item) => sum + item.value, 0); return <Panel className="overview-risk"><div className="panel-heading"><div><p className="eyebrow">RISK DISTRIBUTION</p><h3>Complete local database</h3></div></div><div className="overview-donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={values} dataKey="value" innerRadius={47} outerRadius={68} paddingAngle={3} stroke="none" isAnimationActive={false}>{values.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie></PieChart></ResponsiveContainer><div><strong>{formatCount(total)}</strong><span>results</span></div></div><div className="overview-risk-list">{values.map((item) => <span key={item.name}><i style={{ background: item.color }} /><b>{item.name}</b><em>{formatCount(item.value)}</em><small>{total ? `${Math.round(item.value / total * 100)}%` : "0%"}</small></span>)}</div></Panel>; }

export function StorageCard({ storage }: { storage?: SystemOverview["storage"] }) { return <Panel className="overview-storage"><div className="panel-heading"><div><p className="eyebrow">STORAGE OVERVIEW</p><h3>Local storage capacity</h3><p>Drive health monitoring will be available here when collected.</p></div><HardDrive size={20} /></div>{storage?.length ? storage.map((drive) => <div className="overview-drive" key={drive.drive}><span><strong>{drive.drive}</strong><small>{drive.filesystem}</small></span><div><i><b style={{ width: `${drive.capacity ? Math.min(100, Math.round((drive.capacity - drive.free) / drive.capacity * 100)) : 0}%` }} /></i><small>{bytes(drive.capacity - drive.free)} used of {bytes(drive.capacity)}</small></div><strong>{bytes(drive.free)} free</strong></div>) : <Unavailable />}</Panel>; }

export function HardwareCard({ system }: { system?: SystemOverview }) { const rows = system ? [["CPU usage", `${system.health.cpuUsagePercent}%`], ["RAM usage", `${system.health.memoryUsagePercent}%`], ["Disk usage", system.health.diskUsagePercent === undefined ? "Not Available" : `${system.health.diskUsagePercent}%`], ["GPU usage", "Not Available"], ["Temperature", "Not Available"]] : []; return <Panel className="overview-hardware"><div className="panel-heading"><div><p className="eyebrow">HARDWARE HEALTH</p><h3>Live local utilization</h3></div><Activity size={20} /></div><div className="overview-list">{rows.length ? rows.map(([label, value]) => <Info key={label} label={label} value={value} />) : <Unavailable />}</div></Panel>; }

export function ScanQueueCard({ scan }: { scan: ScanOverview }) { const queued = scan.active ? Math.max(0, scan.total - scan.completed) : 0; return <Panel className="overview-queue"><div className="panel-heading"><div><p className="eyebrow">SCAN QUEUE</p><h3>{scan.active ? "Analysis in progress" : "No active scan"}</h3><p>{scan.active ? scan.currentPath || "Preparing local analysis" : "Start a scan to populate the intelligent queue."}</p></div><ScanSearch size={20} /></div><div className="overview-queue-grid"><Info label="Currently scanning" value={scan.active ? "Yes" : "No"} /><Info label="Queued files" value={formatCount(queued)} /><Info label="Completed" value={formatCount(scan.completed)} /><Info label="Skipped" value={scan.cacheSkipped === undefined ? "Not Available" : formatCount(scan.cacheSkipped)} /><Info label="Cache hits" value={scan.cacheHits === undefined ? "Not Available" : formatCount(scan.cacheHits)} /><Info label="Throughput" value={scan.throughputPerSecond === undefined ? "Not Available" : `${scan.throughputPerSecond.toFixed(1)} files/s`} /><Info label="Estimated remaining" value={scan.estimatedRemainingMs === undefined ? "Not Available" : duration(scan.estimatedRemainingMs / 1000)} /><Info label="Worker threads" value={scan.workersTotal === undefined ? "Not Available" : `${scan.workersActive ?? 0} / ${scan.workersTotal}`} /></div></Panel>; }

export function SecuritySummary({ active, investigations, lastScan }: { active: boolean; investigations: number; lastScan?: string }) { const messages = [active ? "Realtime protection is active." : "Realtime protection needs attention.", investigations ? `${formatCount(investigations)} file${investigations === 1 ? " requires" : "s require"} investigation.` : "No files currently require investigation.", lastScan ? `Last analysis: ${relativeTime(lastScan)}.` : "No completed analysis has been retained yet."]; return <Panel className={`overview-summary ${active && !investigations ? "healthy" : "attention"}`}><ShieldCheck size={25} /><div><p className="eyebrow">SECURITY SUMMARY</p><h3>{investigations ? "Review recommended" : active ? "System appears healthy" : "Protection requires review"}</h3>{messages.map((message) => <p key={message}>{message}</p>)}</div></Panel>; }

export function QuickActions({ onScanFile, onScanFolder, onUpdate }: { onScanFile: () => void; onScanFolder: () => void; onUpdate: () => void }) { const actions: Array<{ label: string; icon: typeof Play; to?: string; action?: () => void; disabled?: boolean }> = [{ label: "Quick Scan", icon: Play, to: "/quick-scan" }, { label: "Full Scan", icon: ScanSearch, to: "/full-scan" }, { label: "Deep Scan", icon: ScanSearch, to: "/full-scan" }, { label: "Scan Folder", icon: FolderSearch, action: onScanFolder }, { label: "Scan File", icon: FileSearch, action: onScanFile }, { label: "Open Quarantine", icon: Archive, disabled: true }, { label: "Update Engine", icon: RefreshCw, action: onUpdate }, { label: "Export Report", icon: Upload, to: "/history" }]; return <Panel className="overview-actions"><div className="panel-heading"><div><p className="eyebrow">QUICK ACTIONS</p><h3>Security controls</h3></div></div><div>{actions.map(({ label, icon: Icon, to, action, disabled }) => to ? <Link key={label} to={to}><Icon size={17} />{label}</Link> : <button key={label} type="button" onClick={action} disabled={disabled} title={disabled ? "Not Available" : label}><Icon size={17} />{label}</button>)}</div></Panel>; }

export function RecentActivity({ items, query, onQuery, riskFilter, onRiskFilter, onOpen }: { items: AnalysisItem[]; query: string; onQuery: (value: string) => void; riskFilter: string; onRiskFilter: (value: string) => void; onOpen: (id: string) => void }) { const visible = items.filter((item) => (riskFilter === "all" || item.riskLevel === riskFilter) && `${item.filePath} ${item.recommendation}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8); return <Panel className="overview-recent"><div className="panel-heading"><div><p className="eyebrow">RECENT ACTIVITY</p><h3>Recent analyses</h3><p>Double-click a row to open its full local report.</p></div><Link className="text-link" to="/history">View history</Link></div><div className="overview-filters"><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search local analyses" aria-label="Search local analyses" /><select value={riskFilter} onChange={(event) => onRiskFilter(event.target.value)} aria-label="Filter local analyses"><option value="all">All risks</option><option value="low">Low risk</option><option value="medium">Medium risk</option><option value="high">High risk</option></select></div>{visible.length ? <div className="overview-activity-list">{visible.map((item) => <button type="button" key={item.id} onDoubleClick={() => onOpen(item.id)}><span className="file-dot">{item.metadata.extension?.slice(1, 4) || "file"}</span><span><strong>{item.filePath.split(/[\\/]/).pop()}</strong><small>{item.recommendation}</small></span><RiskBadge risk={item.riskLevel} /><strong>{item.finalRiskScore}</strong><time>{relativeTime(item.analyzedAt)}</time></button>)}</div> : <Unavailable message="No local analyses match the current filter." />}</Panel>; }

function Info({ label, value }: { label: string; value: string }) { return <div className="overview-info"><span>{label}</span><strong title={value}>{value}</strong></div>; }
function Unavailable({ message = "Not Available" }: { message?: string }) { return <div className="overview-unavailable">{message}</div>; }
export function formatCount(value: number): string { return new Intl.NumberFormat().format(value); }
function bytes(value: number): string { if (!value) return "0 GB"; return `${(value / 1024 ** 3).toFixed(value >= 1024 ** 3 ? 1 : 0)} GB`; }
function duration(seconds: number): string { const days = Math.floor(seconds / 86400); const hours = Math.floor(seconds % 86400 / 3600); const minutes = Math.floor(seconds % 3600 / 60); return days ? `${days}d ${hours}h` : hours ? `${hours}h ${minutes}m` : `${minutes}m`; }
function dateTime(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "Not Available" : date.toLocaleString(); }
function relativeTime(value: string): string { const elapsed = Date.now() - new Date(value).valueOf(); if (!Number.isFinite(elapsed)) return "Not Available"; const minutes = Math.round(elapsed / 60000); return minutes < 1 ? "Just now" : minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : `${Math.round(minutes / 1440)}d ago`; }